name: CI workflow

# Events
on:push

# List of jobs
job:
  test:
    # runner
    # the virtual enviroment where the pipiline run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 # fetch full history

      - name: Set up Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Run the test ¬code coverage
        run: npm test  -- --coverage

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-actions@v2

      - name: Publish to Chromatic
        uses: chrmaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_ROJECT_TOKEN}}  
      